device: "Tesla V100-SXM2-16GB"

base:
  name: "OpenSLU-test"
  train: True
  test: True
  device: cuda
  seed: 42
  epoch_num: 300
  batch_size: 128

model_manager:
  load_train_state: True
  load_dir: save/joint_bert
  save_dir: save/joint_bert

evaluator:
  best_key: EMA
  eval_by_epoch: true
  # eval_step: 1800
  metric:
    - intent_acc
    - slot_f1
    - EMA

accelerator:
  use_accelerator: false

dataset:
  dataset_name: atis

tokenizer:
  _tokenizer_name_: bert-base-uncased
  _padding_side_: right
  _align_mode_: general
  add_special_tokens: true

optimizer:
  _model_target_: torch.optim.AdamW
  _model_partial_: true
  lr: 4e-6
  weight_decay: 1e-8

scheduler:
  _model_target_: transformers.get_scheduler
  _model_partial_: true
  name : "linear"
  num_warmup_steps: 0

model:
  _model_target_: model.open_slu_model.OpenSLUModel
  ignore_index: -100
  encoder:
    _model_target_: model.encoder.AutoEncoder
    encoder_name: bert-base-uncased
    output_dim: 768
    return_with_input: true
    return_sentence_level_hidden: true

  decoder:
    _model_target_: model.decoder.base_decoder.BaseDecoder
    intent_classifier:
      _model_target_: model.decoder.classifier.LinearClassifier
      mode: "intent"
      ignore_index: -100


    slot_classifier:
      _model_target_: model.decoder.classifier.LinearClassifier
      mode: "slot"
      ignore_index: -100